@startuml
title Алгоритм создания заказа
skinparam activity {
    startColor green
    stopColor red
}

|Пользователь|
start
:Перейти\nк оформлению\nзаказа;

|Система|
if (Корзина\nпуста?) then (Да)
  :Показать ошибку\n"Корзина пуста";
  stop
else (Нет)
  if (Пользователь\nавторизован?) then (Нет)
    :Показать форму\nвхода/регистрации;
    |Пользователь|
    :Ввести\nemail и пароль;
    |Система|
    while (Данные\nкорректны?) is (Нет)
      :Показать ошибку\n"Неверный email или пароль";
      |Пользователь|
      :Исправить\nemail и пароль;
      |Система|
    endwhile
    :Авторизовать\nпользователя;
  else (Да)
  endif

  |Пользователь|
  :Указать адрес доставки и\nспособ доставки;
  |Система|
  while (Адрес\nкорректен?) is (Нет)
    :Показать ошибку\n"Некорректный адрес";
    |Пользователь|
    :Исправить\nадрес доставки;
    |Система|
  endwhile
  :Адрес\nпринят;

  |Пользователь|
  :Выбрать\nспособ оплаты\n(онлайн-карта);
  note left: В MVP у нас\nтолько один базовый\nонлайн-эквайринг

  |Система|
  if (Все\nтовары\nв наличии?) then (Нет)
    :Показать ошибку\n"Некоторые товары\nнедоступны";
    |Пользователь|
    :Обновить корзину;
    stop
  else (Да)
    |Пользователь|
    :Подтвердить\nзаказ;
    |Система|
    fork
      :Сохранить\nзаказ в БД;
    fork again
      :Отправить\nemail-уведомление;
    end fork
    :Завершить\nоформление;
    stop
  endif
endif
@enduml