@startuml
title Создание заказа
skinparam activity {
startColor green
endColor red
stopColor red
}

swimlane Клиент
  start
  : Переход к оформлению\nкорзины с товарами;
  note 
    POST/checkout
  end note
swimlane Сервер
      if (Корзина\nне найдена?) then (Да)
swimlane Клиент
        :Корзина\nне найдена;
        note
          404 Not Found
          error "cart_not_found"
        end note
        stop
      endif
swimlane Сервер
        if (Токен\nне валидный/\nне актуальный?) then (Да)
swimlane Клиент
          :Не авторизован;
          note
            401 Unauthorized
          end note
          stop
          else
swimlane Сервер
            if (Корзина не принадлежит\nпользователю\nиз токена?) then (Да)
swimlane Клиент
              :Несовпадение\nтокена и корзины;
              note
                403 Forbidden
                error "cart not owened"
              end note
              stop
              else
              :Ввод\nадреса;
        endif
            endif
swimlane Сервер
              if (Адрес\nне\nвалиден?) then (Да)
swimlane Клиент
                :Невалидный\nадресс;
                note
                 400 Bad Request
                  error "invalid address"
                end note
                stop
                else
swimlane Сервер
                if (Есть отсутствующие\nтовары\nиз корзины?) then (Да)
swimlane Клиент
                  :Нет\nв наличии;
                   note 
                    409 Conflict
                    error"out of stock"
                  end note
                  stop
                  else
swimlane Сервер
                  :Получить данные\nкозины и товаров;
                  note
                    SELECT из cart_items и products
                    WHERE session_id = :session;
                  end note
                  :Сохранить позиции\nзаказа;
                  note
                  INSERT INTO order_items (...);
                  end note
              endif
                endif
swimlane Клиент
  :Успешно;
  note
    201 Created
  end note
  stop
@enduml